In [8]:
import numpy as np
x = np.random.random((5,4))
print("x:\n",x)
y = array([random.randint(0,2) for i in range(5)])
print("y:\n",y)

x:
 [[0.93233676 0.7438053  0.6665873  0.30451194]
 [0.94242521 0.97154279 0.65276638 0.66886847]
 [0.34853132 0.26815422 0.90422768 0.87731141]
 [0.5444588  0.67213929 0.88827223 0.15195895]
 [0.39896198 0.82184951 0.92899799 0.34414937]]
y:
 [0 0 0 0 1]


In [9]:
def extract_subset(x,y,y0):
    return x[y==y0]

x0 = extract_subset(x,y,0)
print(x0)

[[0.93233676 0.7438053  0.6665873  0.30451194]
 [0.94242521 0.97154279 0.65276638 0.66886847]
 [0.34853132 0.26815422 0.90422768 0.87731141]
 [0.5444588  0.67213929 0.88827223 0.15195895]]


In [10]:
def min_feature_values(x):
    return np.min(x, axis=0)

print(min_feature_values(x0))

[0.34853132 0.26815422 0.65276638 0.15195895]


In [11]:
def make_gaussian_dataset(n0, n1, mu0, mu1):
    d = 2
    x0 = np.random.randn(n0, d) + mu0
    x1 = np.random.randn(n1, d) + mu1

    y0 = np.zeros(n0)
    y1 = np.ones(n1)

    x = np.vstack((x0, x1))
    y = np.hstack((y0, y1))
    return x, y

xn, yn = make_gaussian_dataset(10, 10, [-1, -1], [+1, +1])
print('xn:\n', xn)
print('yn:\n', yn)

xn:
 [[-1.25527408 -1.13218567]
 [-0.72595517  0.02063838]
 [-0.20590476 -0.85263741]
 [-1.55489217 -2.61360486]
 [ 0.00311925 -1.90436481]
 [-1.88785935 -1.62275237]
 [-1.82307186 -1.11002003]
 [-1.50739671  0.27309477]
 [-0.68800091  0.29405307]
 [-0.79596887 -1.84366359]
 [-0.48201695  1.00556535]
 [ 0.22057959  0.46912953]
 [ 2.91013542  0.13156094]
 [ 0.75697611  1.89350701]
 [ 1.52307448  1.73259319]
 [ 0.02701766  1.5730398 ]
 [ 2.15373787  0.21972888]
 [ 0.48623687  0.86359831]
 [ 0.79511489  0.51063992]
 [ 0.83993562  2.30803899]]
yn:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
